name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        # Required for Next.js to know this is a production build
        NODE_ENV: production

    - name: Export Static Pages
      run: npm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # Directory where the build output is stored
